# name = "help-me-pass-u_"  # Replace with your Worker name
compatibility_date = "2025-05-16"
main = "index.js"  # Path to your Worker script

# Environment variables (optional, for reference; actual values are set in Cloudflare UI)
[vars]
UPSTREAM_HOST = ""  # Placeholder; actual value set in Cloudflare UI
UPSTREAM_PORT = ""  # Placeholder
UPSTREAM_PATH = "/"  # Placeholder
